# -*- coding: utf-8 -*-
"""Sumarize Content : Text To Speech.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19Y96L8z7wmO7GaLSPd6h3n6iLBkrJT_P
"""

# @title Install OpenAi
!pip install openai

# @title Import files from Colab and Upload the file
from google.colab import files
uploaded = files.upload()

# @title Install Pdfx and import Pdfx
!pip install Pdfx
import pdfx

# @title Reading the pdf
import pdfx
pdf=pdfx.PDFx("example1.pdf")
pdf_content=pdf.get_text()

pip install langchain

pip install tiktoken

# @title
from langchain.docstore.document import Document
from langchain.text_splitter import CharacterTextSplitter

# @title
model_name="gpt-3.5-turbo"
text_splitter=CharacterTextSplitter.from_tiktoken_encoder(model_name=model_name)

texts=text_splitter.split_text(pdf_content)
docs= [Document(page_content=t) for t in texts]

pip install langchain-openai

from langchain_openai import ChatOpenAI
import os

from google.colab import userdata
OPENAI_API_KEY=userdata.get('OpenAi')

llm=ChatOpenAI(
    temperature=0,
    openai_api_key=OPENAI_API_KEY,
    model_name=model_name,
)

from langchain.prompts import PromptTemplate
prompt_template=PromptTemplate(
    input_variables=["context"],
    template="Summarize the following content:{content}"
)

prompt_template="""SUMARIZE the following content:{text}"""
prompt=PromptTemplate(template=prompt_template,input_variables=["text"])

from langchain.chains.combine_documents.stuff import StuffDocumentsChain
from langchain.chains import LLMChain

llm_chain=LLMChain(llm=llm,prompt=prompt)

chain=StuffDocumentsChain(llm_chain=llm_chain,document_variable_name="text")

summary=chain.invoke(docs)

import textwrap

summary_text=summary.get('output_text','No summary available')
print(textwrap.fill(summary_text,width=100))

!pip install gTTs

!pip install ipython

from gtts import gTTS

from IPython.display import Audio

text=summary_text
tts=gTTS(text=text,lang='en')
tts.save('summary.mp3')
Audio("summary.mp3",autoplay=True)



"""
**Thank You😉**
**Done By Manikandan M**"""